on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello to me
    steps:
      - name: Test it
        uses: DamianReeves/sbt-maven-publish@master
        run: |
          echo 'HOME: $HOME'
